#!/bin/bash

echo "Metasploit5 Install With Features"
echo

sudo apt update && sudo apt install -y git autoconf build-essential libpcap-dev libpq-dev zlib1g-dev libsqlite3-dev

sudo apt install ruby-dev

sudo apt-get install postgresql

cd /opt 
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall

cd /opt/metasploit-framework

cd /opt/metasploit-framework/
gem install bundler
bundle install

git clone https://github.com/rapid7/metasploit-framework.wiki.git
git clone https://github.com/DynamicDesignz/mad-metasploit.git
git clone https://github.com/DynamicDesignz/payloads.git
git clone https://github.com/DynamicDesignz/metasploit-payloads.git
git clone https://github.com/darkoperator/Metasploit-Plugins.git

