#!/bin/bash

echo 
echo "Metasploit5 Install With Features"
echo

sudo apt-get install build-essential libreadline-dev libssl-dev libpq5 libpq-dev libreadline5 libsqlite3-dev libpcap-dev git-core autoconf postgresql pgadmin3 curl zlib1g-dev libxml2-dev libxslt1-dev libyaml-dev curl zlib1g-dev gawk bison libffi-dev libgdbm-dev libncurses5-dev libtool sqlite3 libgmp-dev gnupg2 dirmngr
sudo apt update && sudo apt install -y git autoconf build-essential libpcap-dev libpq-dev zlib1g-dev libsqlite3-dev

sudo add-apt-repository -y ppa:webupd8team/java

sudo apt install ruby-dev

sudo apt-get install postgresql

cd /opt 
git clone https://github.com/rapid7/metasploit-framework.git
wget https://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run

sudo su postgres

createuser msfuser -S -R -P

createdb msfdb -O msfuser

exit

sudo update-rc.d postgresql enable



#curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
#  chmod 755 msfinstall && \
#  ./msfinstall

cd /opt/metasploit-framework

git clone https://github.com/rapid7/metasploit-framework.wiki.git
git clone https://github.com/DynamicDesignz/mad-metasploit.git
git clone https://github.com/DynamicDesignz/payloads.git
git clone https://github.com/DynamicDesignz/metasploit-payloads.git
git clone https://github.com/darkoperator/Metasploit-Plugins.git

cd /opt/metasploit-framework/
gem install bundler
bundle install

terminator sudo msfconsole
exit
